(library (soda test file-state)
  (export run-file-state-tests!)
  (import (rnrs)
          (soda kernel resource)
          (soda packages file-format)
          (soda packages file-state))

  (define (run-file-state-tests!)
    (let* ([state (make-file-state)]
           [resource (make-resource 'file "/tmp/soda-file-state-test")]
           [format (make-default-file-format)]
           [binding (make-file-binding resource 'version 'lock format)]
           [conflict (make-file-conflict 7 resource 'version 'modified 'pending)])
      (file-state-set-binding! state 7 binding)
      (unless (eq? (file-state-binding state 7) binding)
        (error 'file-state-tests "binding lookup did not retain identity"))
      (let-values ([(buffer-id found)
                    (file-state-binding-at-path state "/tmp/soda-file-state-test")])
        (unless (and (= buffer-id 7) (eq? found binding))
          (error 'file-state-tests "path lookup did not find the binding")))
      (let-values ([(buffer-id found)
                    (file-state-binding-at-path state "/tmp/missing")])
        (unless (and (not buffer-id) (not found))
          (error 'file-state-tests "missing path lookup returned a binding")))
      (file-state-set-conflict! state 7 conflict)
      (file-conflict-status-set! conflict 'ignored)
      (unless (and (eq? (file-state-conflict state 7) conflict)
                   (eq? (file-conflict-status conflict) 'ignored))
        (error 'file-state-tests "conflict state was not retained"))
      (file-state-delete-buffer! state 7)
      (unless (and (not (file-state-binding state 7 #f))
                   (not (file-state-conflict state 7 #f)))
        (error 'file-state-tests "buffer cleanup was not atomic"))))
)
