(library (soda packages base fundamental-keymap)
  (export install-fundamental-keymap!)
  (import (rnrs) (soda host input) (soda host input-event))

  (define (control character)
    (make-key-stroke 'character (char->integer character) 4))
  (define (plain key codepoint) (make-key-stroke key codepoint 0))
  (define (meta character)
    (make-key-stroke 'character (char->integer character) 2))
  (define (bind! keymap sequence command) (keymap-bind! keymap sequence command))

  (define (install-fundamental-keymap! keymap)
    (unless (keymap? keymap)
      (assertion-violation 'install-fundamental-keymap! "expected a Keymap" keymap))
    (for-each
      (lambda (entry) (bind! keymap (car entry) (cdr entry)))
      (list
        (cons (list (control #\b)) 'fundamental.backward-char)
        (cons (list (control #\f)) 'fundamental.forward-char)
        (cons (list (control #\a)) 'fundamental.beginning-of-line)
        (cons (list (control #\e)) 'fundamental.end-of-line)
        (cons (list (control #\p)) 'fundamental.previous-line)
        (cons (list (control #\n)) 'fundamental.next-line)
        (cons (list (control #\j)) 'fundamental.newline)
        (cons (list (control #\t)) 'fundamental.transpose-characters)
        (cons (list (control #\l)) 'fundamental.recenter)
        (cons (list (control #\v)) 'fundamental.scroll-down)
        (cons (list (make-key-stroke 'character (char->integer #\space) 4)) 'fundamental.set-mark)
        (cons (list (control #\6)) 'fundamental.set-mark)
        (cons (list (control #\^)) 'fundamental.set-mark)
        (cons (list (control #\w)) 'fundamental.kill-region)
        (cons (list (control #\y)) 'fundamental.yank)
        (cons (list (control #\o)) 'fundamental.open-line)
        (cons (list (control #\k)) 'fundamental.kill-line)
        (cons (list (meta #\b)) 'fundamental.backward-word)
        (cons (list (meta #\f)) 'fundamental.forward-word)
        (cons (list (meta #\w)) 'fundamental.copy-region)
        (cons (list (meta #\d)) 'fundamental.kill-word)
        (cons (list (meta #\v)) 'fundamental.scroll-up)
        (cons (list (meta #\r)) 'fundamental.move-to-window-center)
        (cons (list (make-key-stroke 'backspace #f 2)) 'fundamental.backward-kill-word)
        (cons (list (control #\d)) 'fundamental.delete-forward)
        (cons (list (control #\_)) 'fundamental.goto-line)
        (cons (list (control #\x) (plain 'character (char->integer #\h)))
              'fundamental.mark-whole-buffer)
        (cons (list (control #\x) (control #\x)) 'fundamental.exchange-point-and-mark)
        (cons (list (control #\x) (plain 'character (char->integer #\>))) 'fundamental.indent-lines)
        (cons (list (control #\x) (plain 'character (char->integer #\<))) 'fundamental.unindent-lines)
        (cons (list (meta #\])) 'fundamental.matching-delimiter)
        (cons (list (meta #\<)) 'fundamental.beginning-of-buffer)
        (cons (list (meta #\>)) 'fundamental.end-of-buffer)
        (cons (list (meta #\q)) 'fundamental.fill-paragraph)
        (cons (list (plain 'left #f)) 'fundamental.backward-char)
        (cons (list (plain 'right #f)) 'fundamental.forward-char)
        (cons (list (plain 'up #f)) 'fundamental.previous-line)
        (cons (list (plain 'down #f)) 'fundamental.next-line)
        (cons (list (plain 'home #f)) 'fundamental.beginning-of-line)
        (cons (list (plain 'end #f)) 'fundamental.end-of-line)
        (cons (list (plain 'page-up #f)) 'fundamental.scroll-up)
        (cons (list (plain 'page-down #f)) 'fundamental.scroll-down)
        (cons (list (plain 'tab #f)) 'fundamental.insert-tab)
        (cons (list (plain 'backspace #f)) 'fundamental.delete-backward)
        (cons (list (plain 'delete #f)) 'fundamental.delete-forward)
        (cons (list (plain 'enter #f)) 'fundamental.newline)))
    keymap)
)
