(library (soda packages search-keymap)
  (export make-search-keymap)
  (import (rnrs)
          (soda host input)
          (soda host input-event))

  (define (stroke character modifiers)
    (make-key-stroke 'character (char->integer character) modifiers))

  (define (make-search-keymap)
    (let ([keymap (make-keymap 'search)])
      (keymap-bind! keymap (list (stroke #\s 4)) 'search.forward)
      (keymap-bind! keymap (list (stroke #\r 4)) 'search.backward)
      (keymap-bind! keymap (list (stroke #\% 2)) 'search.query-replace)
      (keymap-bind! keymap (list (stroke #\s 2)) 'search.next)
      (keymap-bind! keymap (list (stroke #\C 2)) 'search.toggle-case-sensitive)
      (keymap-bind! keymap (list (stroke #\` 2)) 'search.toggle-whole-word)
      (keymap-bind! keymap (list (stroke #\r 2)) 'search.toggle-regular-expression)
      (keymap-bind! keymap (list (stroke #\s 3)) 'search.previous)
      keymap))
)
